/*
 * dma_config.h
 *
 *  Created on: Mar 28, 2026
 *      Author: ghrug
 */

#include "dma_drv.h"

#ifndef DMA_CONFIG_H_
#define DMA_CONFIG_H_

#define DMA1_STREAM0_EN
//#define DMA1_STREAM1_EN
//#define DMA1_STREAM2_EN
//#define DMA1_STREAM3_EN
//#define DMA1_STREAM4_EN
//#define DMA1_STREAM5_EN
//#define DMA1_STREAM6_EN
//#define DMA1_STREAM7_EN
//
//#define DMA2_STREAM0_EN
//#define DMA2_STREAM1_EN
//#define DMA2_STREAM2_EN
//#define DMA2_STREAM3_EN
//#define DMA2_STREAM4_EN
//#define DMA2_STREAM5_EN
//#define DMA2_STREAM6_EN
//#define DMA2_STREAM7_EN




// DMA1 Stream 0

#ifdef DMA1_STREAM0_EN

#define DMA1_STREAM0_SRC_ADDR 0x0
#define DMA1_STREAM0_DST_ADDR 0x0
#define DMA1_STREAM0_DATA_WIDTH BIT_16
#define DMA1_STREAM0_DIRECTION P2M
#define DMA1_STREAM0_BUFFER_SIZE 256
#define DMA1_STREAM0_TRANSFER_MODE ONESHOT
#define DMA1_STREAM0_PRIORITY 2

#define DMA1_STREAM0_FEIF_EN 0
#define DMA1_STREAM0_DMEIF_EN 0
#define DMA1_STREAM0_TEIF_EN 0
#define DMA1_STREAM0_HTIF_EN 0
#define DMA1_STREAM0_TCIF_EN 0

#endif //DMA1_STREAM0_EN

// DMA1 Stream 1
#ifdef DMA1_STREAM1_EN

#define DMA1_STREAM1_SRC_ADDR
#define DMA1_STREAM1_DST_ADDR
#define DMA1_STREAM1_DATA_WIDTH BIT_16
#define DMA1_STREAM1_DIRECTION P2M
#define DMA1_STREAM1_BUFFER_SIZE 256
#define DMA1_STREAM1_TRANSFER_MODE ONESHOT
#define DMA1_STREAM1_PRIORITY 2

#define DMA1_STREAM1_FEIF_EN 0
#define DMA1_STREAM1_DMEIF_EN 0
#define DMA1_STREAM1_TEIF_EN 0
#define DMA1_STREAM1_HTIF_EN 0
#define DMA1_STREAM1_TCIF_EN 0

#endif //DMA1_STREAM1_EN

// DMA1 Stream 2
#ifdef DMA1_STREAM2_EN

#define DMA1_STREAM2_SRC_ADDR
#define DMA1_STREAM2_DST_ADDR
#define DMA1_STREAM2_DATA_WIDTH BIT_16
#define DMA1_STREAM2_DIRECTION P2M
#define DMA1_STREAM2_BUFFER_SIZE 256
#define DMA1_STREAM2_TRANSFER_MODE ONESHOT
#define DMA1_STREAM2_PRIORITY 2

#define DMA1_STREAM2_FEIF_EN 0
#define DMA1_STREAM2_DMEIF_EN 0
#define DMA1_STREAM2_TEIF_EN 0
#define DMA1_STREAM2_HTIF_EN 0
#define DMA1_STREAM2_TCIF_EN 0

#endif //DMA1_STREAM2_EN

// DMA1 Stream 3
#ifdef DMA1_STREAM3_EN

#define DMA1_STREAM3_SRC_ADDR
#define DMA1_STREAM3_DST_ADDR
#define DMA1_STREAM3_DATA_WIDTH BIT_16
#define DMA1_STREAM3_DIRECTION P2M
#define DMA1_STREAM3_BUFFER_SIZE 256
#define DMA1_STREAM3_TRANSFER_MODE ONESHOT
#define DMA1_STREAM3_PRIORITY 2

#define DMA1_STREAM3_FEIF_EN 0
#define DMA1_STREAM3_DMEIF_EN 0
#define DMA1_STREAM3_TEIF_EN 0
#define DMA1_STREAM3_HTIF_EN 0
#define DMA1_STREAM3_TCIF_EN 0

#endif //DMA1_STREAM3_EN

// DMA1 Stream 4
#ifdef DMA1_STREAM4_EN

#define DMA1_STREAM4_SRC_ADDR
#define DMA1_STREAM4_DST_ADDR
#define DMA1_STREAM4_DATA_WIDTH BIT_16
#define DMA1_STREAM4_DIRECTION P2M
#define DMA1_STREAM4_BUFFER_SIZE 256
#define DMA1_STREAM4_TRANSFER_MODE ONESHOT
#define DMA1_STREAM4_PRIORITY 2

#define DMA1_STREAM4_FEIF_EN 0
#define DMA1_STREAM4_DMEIF_EN 0
#define DMA1_STREAM4_TEIF_EN 0
#define DMA1_STREAM4_HTIF_EN 0
#define DMA1_STREAM4_TCIF_EN 0

#endif //DMA1_STREAM4_EN

// DMA1 Stream 5
#ifdef DMA1_STREAM5_EN

#define DMA1_STREAM5_SRC_ADDR
#define DMA1_STREAM5_DST_ADDR
#define DMA1_STREAM5_DATA_WIDTH BIT_16
#define DMA1_STREAM5_DIRECTION P2M
#define DMA1_STREAM5_BUFFER_SIZE 256
#define DMA1_STREAM5_TRANSFER_MODE ONESHOT
#define DMA1_STREAM5_PRIORITY 2

#define DMA1_STREAM5_FEIF_EN 0
#define DMA1_STREAM5_DMEIF_EN 0
#define DMA1_STREAM5_TEIF_EN 0
#define DMA1_STREAM5_HTIF_EN 0
#define DMA1_STREAM5_TCIF_EN 0

#endif //DMA1_STREAM5_EN

// DMA1 Stream 6
#ifdef DMA1_STREAM6_EN

#define DMA1_STREAM6_SRC_ADDR
#define DMA1_STREAM6_DST_ADDR
#define DMA1_STREAM6_DATA_WIDTH BIT_16
#define DMA1_STREAM6_DIRECTION P2M
#define DMA1_STREAM6_BUFFER_SIZE 256
#define DMA1_STREAM6_TRANSFER_MODE ONESHOT
#define DMA1_STREAM6_PRIORITY 2

#define DMA1_STREAM6_FEIF_EN 0
#define DMA1_STREAM6_DMEIF_EN 0
#define DMA1_STREAM6_TEIF_EN 0
#define DMA1_STREAM6_HTIF_EN 0
#define DMA1_STREAM6_TCIF_EN 0

#endif //DMA1_STREAM6_EN

// DMA1 Stream 7
#ifdef DMA1_STREAM7_EN

#define DMA1_STREAM7_SRC_ADDR
#define DMA1_STREAM7_DST_ADDR
#define DMA1_STREAM7_DATA_WIDTH BIT_16
#define DMA1_STREAM7_DIRECTION P2M
#define DMA1_STREAM7_BUFFER_SIZE 256
#define DMA1_STREAM7_TRANSFER_MODE ONESHOT
#define DMA1_STREAM7_PRIORITY 2

#define DMA1_STREAM7_FEIF_EN 0
#define DMA1_STREAM7_DMEIF_EN 0
#define DMA1_STREAM7_TEIF_EN 0
#define DMA1_STREAM7_HTIF_EN 0
#define DMA1_STREAM7_TCIF_EN 0

#endif //DMA1_STREAM7_EN

// DMA2 Stream 0
#ifdef DMA2_STREAM0_EN

#define DMA2_STREAM0_SRC_ADDR
#define DMA2_STREAM0_DST_ADDR
#define DMA2_STREAM0_DATA_WIDTH BIT_16
#define DMA2_STREAM0_DIRECTION P2M
#define DMA2_STREAM0_BUFFER_SIZE 256
#define DMA2_STREAM0_TRANSFER_MODE ONESHOT
#define DMA2_STREAM0_PRIORITY 2

#define DMA2_STREAM0_FEIF_EN 0
#define DMA2_STREAM0_DMEIF_EN 0
#define DMA2_STREAM0_TEIF_EN 0
#define DMA2_STREAM0_HTIF_EN 0
#define DMA2_STREAM0_TCIF_EN 0

#endif //DMA2_STREAM0_EN

// DMA2 Stream 1
#ifdef DMA2_STREAM1_EN

#define DMA2_STREAM1_SRC_ADDR
#define DMA2_STREAM1_DST_ADDR
#define DMA2_STREAM1_DATA_WIDTH BIT_16
#define DMA2_STREAM1_DIRECTION P2M
#define DMA2_STREAM1_BUFFER_SIZE 256
#define DMA2_STREAM1_TRANSFER_MODE ONESHOT
#define DMA2_STREAM1_PRIORITY 2

#define DMA2_STREAM1_FEIF_EN 0
#define DMA2_STREAM1_DMEIF_EN 0
#define DMA2_STREAM1_TEIF_EN 0
#define DMA2_STREAM1_HTIF_EN 0
#define DMA2_STREAM1_TCIF_EN 0

#endif //DMA2_STREAM1_EN

// DMA2 Stream 2
#ifdef DMA2_STREAM2_EN

#define DMA2_STREAM2_SRC_ADDR
#define DMA2_STREAM2_DST_ADDR
#define DMA2_STREAM2_DATA_WIDTH BIT_16
#define DMA2_STREAM2_DIRECTION P2M
#define DMA2_STREAM2_BUFFER_SIZE 256
#define DMA2_STREAM2_TRANSFER_MODE ONESHOT
#define DMA2_STREAM2_PRIORITY 2

#define DMA2_STREAM2_FEIF_EN 0
#define DMA2_STREAM2_DMEIF_EN 0
#define DMA2_STREAM2_TEIF_EN 0
#define DMA2_STREAM2_HTIF_EN 0
#define DMA2_STREAM2_TCIF_EN 0

#endif //DMA2_STREAM2_EN

// DMA2 Stream 3
#ifdef DMA2_STREAM3_EN

#define DMA2_STREAM3_SRC_ADDR
#define DMA2_STREAM3_DST_ADDR
#define DMA2_STREAM3_DATA_WIDTH BIT_16
#define DMA2_STREAM3_DIRECTION P2M
#define DMA2_STREAM3_BUFFER_SIZE 256
#define DMA2_STREAM3_TRANSFER_MODE ONESHOT
#define DMA2_STREAM3_PRIORITY 2

#define DMA2_STREAM3_FEIF_EN 0
#define DMA2_STREAM3_DMEIF_EN 0
#define DMA2_STREAM3_TEIF_EN 0
#define DMA2_STREAM3_HTIF_EN 0
#define DMA2_STREAM3_TCIF_EN 0

#endif //DMA2_STREAM3_EN

// DMA2 Stream 4
#ifdef DMA2_STREAM4_EN

#define DMA2_STREAM4_SRC_ADDR
#define DMA2_STREAM4_DST_ADDR
#define DMA2_STREAM4_DATA_WIDTH BIT_16
#define DMA2_STREAM4_DIRECTION P2M
#define DMA2_STREAM4_BUFFER_SIZE 256
#define DMA2_STREAM4_TRANSFER_MODE ONESHOT
#define DMA2_STREAM4_PRIORITY 2

#define DMA2_STREAM4_FEIF_EN 0
#define DMA2_STREAM4_DMEIF_EN 0
#define DMA2_STREAM4_TEIF_EN 0
#define DMA2_STREAM4_HTIF_EN 0
#define DMA2_STREAM4_TCIF_EN 0

#endif //DMA2_STREAM4_EN

// DMA2 Stream 5
#ifdef DMA2_STREAM5_EN

#define DMA2_STREAM5_SRC_ADDR
#define DMA2_STREAM5_DST_ADDR
#define DMA2_STREAM5_DATA_WIDTH BIT_16
#define DMA2_STREAM5_DIRECTION P2M
#define DMA2_STREAM5_BUFFER_SIZE 256
#define DMA2_STREAM5_TRANSFER_MODE ONESHOT
#define DMA2_STREAM5_PRIORITY 2

#define DMA2_STREAM5_FEIF_EN 0
#define DMA2_STREAM5_DMEIF_EN 0
#define DMA2_STREAM5_TEIF_EN 0
#define DMA2_STREAM5_HTIF_EN 0
#define DMA2_STREAM5_TCIF_EN 0

#endif //DMA2_STREAM5_EN

// DMA2 Stream 6
#ifdef DMA2_STREAM6_EN

#define DMA2_STREAM6_SRC_ADDR
#define DMA2_STREAM6_DST_ADDR
#define DMA2_STREAM6_DATA_WIDTH BIT_16
#define DMA2_STREAM6_DIRECTION P2M
#define DMA2_STREAM6_BUFFER_SIZE 256
#define DMA2_STREAM6_TRANSFER_MODE ONESHOT
#define DMA2_STREAM6_PRIORITY 2

#define DMA2_STREAM6_FEIF_EN 0
#define DMA2_STREAM6_DMEIF_EN 0
#define DMA2_STREAM6_TEIF_EN 0
#define DMA2_STREAM6_HTIF_EN 0
#define DMA2_STREAM6_TCIF_EN 0

#endif //DMA2_STREAM6_EN

// DMA2 Stream 7
#ifdef DMA2_STREAM7_EN

#define DMA2_STREAM7_SRC_ADDR
#define DMA2_STREAM7_DST_ADDR
#define DMA2_STREAM7_DATA_WIDTH BIT_16
#define DMA2_STREAM7_DIRECTION P2M
#define DMA2_STREAM7_BUFFER_SIZE 256
#define DMA2_STREAM7_TRANSFER_MODE ONESHOT
#define DMA2_STREAM7_PRIORITY 2

#define DMA2_STREAM7_FEIF_EN 0
#define DMA2_STREAM7_DMEIF_EN 0
#define DMA2_STREAM7_TEIF_EN 0
#define DMA2_STREAM7_HTIF_EN 0
#define DMA2_STREAM7_TCIF_EN 0

#endif //DMA2_STREAM7_EN

#endif /* DMA_CONFIG_H_ */
