/*
 * dma_config.h
 *
 *  Created on: Mar 28, 2026
 *      Author: ghrug
 */

#include "dma_drv.h"

#ifndef DMA_CONFIG_H_
#define DMA_CONFIG_H_

#define DMA1_STREAM0_EN
//#define DMA1_STREAM1_EN
//#define DMA1_STREAM2_EN
//#define DMA1_STREAM3_EN
//#define DMA1_STREAM4_EN
//#define DMA1_STREAM5_EN
//#define DMA1_STREAM6_EN
//#define DMA1_STREAM7_EN
//
//#define DMA2_STREAM0_EN
//#define DMA2_STREAM1_EN
//#define DMA2_STREAM2_EN
//#define DMA2_STREAM3_EN
//#define DMA2_STREAM4_EN
//#define DMA2_STREAM5_EN
//#define DMA2_STREAM6_EN
//#define DMA2_STREAM7_EN


// DMA1 Stream 0

#ifdef DMA1_STREAM0_EN

#define DMA1_STREAM0_SRC_ADDR
#define DMA1_STREAM0_DST_ADDR
#define DMA1_STREAM0_DATA_WIDTH BIT_16
#define DMA1_STREAM0_DIRECTION P2M
#define DMA1_STREAM0_BUFFER_SIZE 256
#define DMA1_STREAM0_CIRCULAR 0
#define DMA1_STREAM0_PRIORITY 2

#endif //DMA1_STREAM0_EN

// DMA1 Stream 1
#ifdef DMA1_STREAM1_EN

#define DMA1_STREAM1_SRC_ADDR
#define DMA1_STREAM1_DST_ADDR
#define DMA1_STREAM1_DATA_WIDTH BIT_16
#define DMA1_STREAM1_DIRECTION P2M
#define DMA1_STREAM1_BUFFER_SIZE 256
#define DMA1_STREAM1_CIRCULAR 0
#define DMA1_STREAM1_PRIORITY 2

#endif //DMA1_STREAM1_EN

// DMA1 Stream 2
#ifdef DMA1_STREAM2_EN

#define DMA1_STREAM2_SRC_ADDR
#define DMA1_STREAM2_DST_ADDR
#define DMA1_STREAM2_DATA_WIDTH BIT_16
#define DMA1_STREAM2_DIRECTION P2M
#define DMA1_STREAM2_BUFFER_SIZE 256
#define DMA1_STREAM2_CIRCULAR 0
#define DMA1_STREAM2_PRIORITY 2

#endif //DMA1_STREAM2_EN

// DMA1 Stream 3
#ifdef DMA1_STREAM3_EN

#define DMA1_STREAM3_SRC_ADDR
#define DMA1_STREAM3_DST_ADDR
#define DMA1_STREAM3_DATA_WIDTH BIT_16
#define DMA1_STREAM3_DIRECTION P2M
#define DMA1_STREAM3_BUFFER_SIZE 256
#define DMA1_STREAM3_CIRCULAR 0
#define DMA1_STREAM3_PRIORITY 2

#endif //DMA1_STREAM3_EN

// DMA1 Stream 4
#ifdef DMA1_STREAM4_EN

#define DMA1_STREAM4_SRC_ADDR
#define DMA1_STREAM4_DST_ADDR
#define DMA1_STREAM4_DATA_WIDTH BIT_16
#define DMA1_STREAM4_DIRECTION P2M
#define DMA1_STREAM4_BUFFER_SIZE 256
#define DMA1_STREAM4_CIRCULAR 0
#define DMA1_STREAM4_PRIORITY 2

#endif //DMA1_STREAM4_EN

// DMA1 Stream 5
#ifdef DMA1_STREAM5_EN

#define DMA1_STREAM5_SRC_ADDR
#define DMA1_STREAM5_DST_ADDR
#define DMA1_STREAM5_DATA_WIDTH BIT_16
#define DMA1_STREAM5_DIRECTION P2M
#define DMA1_STREAM5_BUFFER_SIZE 256
#define DMA1_STREAM5_CIRCULAR 0
#define DMA1_STREAM5_PRIORITY 2

#endif //DMA1_STREAM5_EN

// DMA1 Stream 6
#ifdef DMA1_STREAM6_EN

#define DMA1_STREAM6_SRC_ADDR
#define DMA1_STREAM6_DST_ADDR
#define DMA1_STREAM6_DATA_WIDTH BIT_16
#define DMA1_STREAM6_DIRECTION P2M
#define DMA1_STREAM6_BUFFER_SIZE 256
#define DMA1_STREAM6_CIRCULAR 0
#define DMA1_STREAM6_PRIORITY 2

#endif //DMA1_STREAM6_EN

// DMA1 Stream 7
#ifdef DMA1_STREAM7_EN

#define DMA1_STREAM7_SRC_ADDR
#define DMA1_STREAM7_DST_ADDR
#define DMA1_STREAM7_DATA_WIDTH BIT_16
#define DMA1_STREAM7_DIRECTION P2M
#define DMA1_STREAM7_BUFFER_SIZE 256
#define DMA1_STREAM7_CIRCULAR 0
#define DMA1_STREAM7_PRIORITY 2

#endif //DMA1_STREAM7_EN

// DMA2 Stream 0
#ifdef DMA2_STREAM0_EN

#define DMA2_STREAM0_SRC_ADDR
#define DMA2_STREAM0_DST_ADDR
#define DMA2_STREAM0_DATA_WIDTH BIT_16
#define DMA2_STREAM0_DIRECTION P2M
#define DMA2_STREAM0_BUFFER_SIZE 256
#define DMA2_STREAM0_CIRCULAR 0
#define DMA2_STREAM0_PRIORITY 2

#endif //DMA2_STREAM0_EN

// DMA2 Stream 1
#ifdef DMA2_STREAM1_EN

#define DMA2_STREAM1_SRC_ADDR
#define DMA2_STREAM1_DST_ADDR
#define DMA2_STREAM1_DATA_WIDTH BIT_16
#define DMA2_STREAM1_DIRECTION P2M
#define DMA2_STREAM1_BUFFER_SIZE 256
#define DMA2_STREAM1_CIRCULAR 0
#define DMA2_STREAM1_PRIORITY 2

#endif //DMA2_STREAM1_EN

// DMA2 Stream 2
#ifdef DMA2_STREAM2_EN

#define DMA2_STREAM2_SRC_ADDR
#define DMA2_STREAM2_DST_ADDR
#define DMA2_STREAM2_DATA_WIDTH BIT_16
#define DMA2_STREAM2_DIRECTION P2M
#define DMA2_STREAM2_BUFFER_SIZE 256
#define DMA2_STREAM2_CIRCULAR 0
#define DMA2_STREAM2_PRIORITY 2

#endif //DMA2_STREAM2_EN

// DMA2 Stream 3
#ifdef DMA2_STREAM3_EN

#define DMA2_STREAM3_SRC_ADDR
#define DMA2_STREAM3_DST_ADDR
#define DMA2_STREAM3_DATA_WIDTH BIT_16
#define DMA2_STREAM3_DIRECTION P2M
#define DMA2_STREAM3_BUFFER_SIZE 256
#define DMA2_STREAM3_CIRCULAR 0
#define DMA2_STREAM3_PRIORITY 2

#endif //DMA2_STREAM3_EN

// DMA2 Stream 4
#ifdef DMA2_STREAM4_EN

#define DMA2_STREAM4_SRC_ADDR
#define DMA2_STREAM4_DST_ADDR
#define DMA2_STREAM4_DATA_WIDTH BIT_16
#define DMA2_STREAM4_DIRECTION P2M
#define DMA2_STREAM4_BUFFER_SIZE 256
#define DMA2_STREAM4_CIRCULAR 0
#define DMA2_STREAM4_PRIORITY 2

#endif //DMA2_STREAM4_EN

// DMA2 Stream 5
#ifdef DMA2_STREAM5_EN

#define DMA2_STREAM5_SRC_ADDR
#define DMA2_STREAM5_DST_ADDR
#define DMA2_STREAM5_DATA_WIDTH BIT_16
#define DMA2_STREAM5_DIRECTION P2M
#define DMA2_STREAM5_BUFFER_SIZE 256
#define DMA2_STREAM5_CIRCULAR 0
#define DMA2_STREAM5_PRIORITY 2

#endif //DMA2_STREAM5_EN

// DMA2 Stream 6
#ifdef DMA2_STREAM6_EN

#define DMA2_STREAM6_SRC_ADDR
#define DMA2_STREAM6_DST_ADDR
#define DMA2_STREAM6_DATA_WIDTH BIT_16
#define DMA2_STREAM6_DIRECTION P2M
#define DMA2_STREAM6_BUFFER_SIZE 256
#define DMA2_STREAM6_CIRCULAR 0
#define DMA2_STREAM6_PRIORITY 2

#endif //DMA2_STREAM6_EN

// DMA2 Stream 7
#ifdef DMA2_STREAM7_EN

#define DMA2_STREAM7_SRC_ADDR
#define DMA2_STREAM7_DST_ADDR
#define DMA2_STREAM7_DATA_WIDTH BIT_16
#define DMA2_STREAM7_DIRECTION P2M
#define DMA2_STREAM7_BUFFER_SIZE 256
#define DMA2_STREAM7_CIRCULAR 0
#define DMA2_STREAM7_PRIORITY 2

#endif //DMA2_STREAM7_EN

#endif /* DMA_CONFIG_H_ */
