/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <system.h>
#include "led_bsp.h"
#include "uart_bsp.h"
#include "uart_app.h"
#include "global.h"
#include "bdp.h"

#define LINE_BUF_LEN 128

int main(void)
{
    system_init();
    led_bsp_init(&led_1);
    uart_bsp_init(&uart3_bsp);

    while (1) {
        system_service();


        static uint32_t last_counter = 0;
    	if (counter_1s != last_counter) {
    		bsp_led_toggle(&led_1);
    		uart_app_printf(&uart3_bsp, "counter: %lu\r\n", counter_1s);
    		last_counter = counter_1s;
    	}

    }
}

