/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <system.h>
#include "led_bsp.h"
#include "uart_bsp.h"
#include "uart_app.h"
#include "global.h"
#include "bdp.h"

#define LINE_BUF_LEN 128

int main(void)
{
    system_init();
    led_bsp_init(&led_1);
    uart_bsp_init(&uart2_bsp);

    // Direct test - bypass printf
    uart_send(&uart2_bsp.usart, 'A');
    uart_send(&uart2_bsp.usart, 'B');
    uart_send(&uart2_bsp.usart, 'C');
    uart_send(&uart2_bsp.usart, '\r');
    uart_send(&uart2_bsp.usart, '\n');

    uart_app_printf(&uart2_bsp, "BearMetal ready\r\n");

    static char line_buf[LINE_BUF_LEN];

    while (1) {
        kick_watchdog();

        uart_app_run(&uart2_bsp);

        int16_t n = uart_app_read_line(&uart2_bsp, line_buf, LINE_BUF_LEN);
        if (n >= 0) {
            uart_app_send_string(&uart2_bsp, "echo: ");
            uart_app_send_string(&uart2_bsp, line_buf);
            uart_app_send_string(&uart2_bsp, "\r\n");
        }
    }
}

