/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <system.h>
#include "bsp.h"
#include "uart_bsp.h"

static void delay(volatile uint32_t n) { while (n--) __NOP(); }

int main(void)
{
    system_init();
    bsp_init();

    // Timer for LED toggle
    uint32_t led_timer = 0;

    while (1) {
        // Toggle LED every 1000 ms (1 second)
        if (timer_elapsed(&led_timer, 1000)) {
            bsp_led_toggle();
        }

        // This will need to be handeld differently with RTOS
        kick_watchdog();
    }
}

